version: '3.8'

services:
  api:
    image: ${DOCKER_REGISTRY}/kamf-api:${IMAGE_TAG:-latest}
    container_name: ${DEPLOY_PATH:-kamf}-api # 환경별 컨테이너 이름
    restart: unless-stopped
    ports:
      - '${API_PORT:-8000}:8000' # 환경별 외부 포트
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      # Application Environment
      NODE_ENV: ${NODE_ENV:-production}
      SERVER_PORT: 8000 # 내부 포트는 고정
      API_PREFIX: ${API_PREFIX:-api}
      CORS_ORIGIN: ${CORS_ORIGIN}

      # Database Connection (호스트 MySQL)
      DB_HOST: host.docker.internal # 호스트 MySQL 접근
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME:-kamf}
      DB_PASSWORD: ${DB_PASSWORD:-kamf_password}
      DB_NAME: ${DB_NAME} # 환경별 데이터베이스

      # JWT & Authentication
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-1h}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      REFRESH_TOKEN_EXPIRES_IN: ${REFRESH_TOKEN_EXPIRES_IN:-7d}

      # Twilio SMS
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_SERVICE_SID: ${TWILIO_SERVICE_SID}

    networks:
      - kamf-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      timeout: 10s
      retries: 5
      interval: 30s

  web:
    image: ${DOCKER_REGISTRY}/kamf-web:${IMAGE_TAG:-latest}
    container_name: ${DEPLOY_PATH:-kamf}-web # 환경별 컨테이너 이름
    restart: unless-stopped
    ports:
      - '${WEB_PORT:-3000}:3000' # 환경별 외부 포트
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      NEXT_PORT: 3000 # 내부 포트는 고정
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    depends_on:
      - api
    networks:
      - kamf-network
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/']
      timeout: 10s
      retries: 5
      interval: 30s

networks:
  kamf-network:
    driver: bridge
