version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: kamf-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ../mysql-init:/docker-entrypoint-initdb.d
    networks:
      - kamf-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
      interval: 30s

  api:
    image: ${DOCKER_REGISTRY}/kamf-api:${IMAGE_TAG:-latest}
    container_name: kamf-api
    restart: unless-stopped
    environment:
      # Application Environment
      NODE_ENV: ${NODE_ENV:-production}
      SERVER_PORT: ${SERVER_PORT:-8000}
      API_PREFIX: ${API_PREFIX:-api}
      CORS_ORIGIN: ${CORS_ORIGIN}

      # Database Connection
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      # JWT & Authentication
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-1h}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      REFRESH_TOKEN_EXPIRES_IN: ${REFRESH_TOKEN_EXPIRES_IN:-7d}

      # Twilio SMS
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - kamf-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      timeout: 10s
      retries: 5
      interval: 30s

  web:
    image: ${DOCKER_REGISTRY}/kamf-web:${IMAGE_TAG:-latest}
    container_name: kamf-web
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      NEXT_PORT: 3000
    depends_on:
      api:
        condition: service_healthy
    networks:
      - kamf-network
    healthcheck:
      test:
        ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/api/health']
      timeout: 10s
      retries: 5
      interval: 30s

  nginx:
    image: nginx:alpine
    container_name: kamf-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
      - web
    networks:
      - kamf-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      timeout: 5s
      retries: 3
      interval: 30s

volumes:
  mysql_data:

networks:
  kamf-network:
    driver: bridge
